# Generated by Django 5.0.7 on 2026-06-02 17:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_cache_memory_resume_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memory',
            unique_together={('user', 'key')},
        ),
    ]
