# Generated by Django 5.0.7 on 2026-06-02 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_alter_memory_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nlpevent',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'NLP events'},
        ),
        migrations.AddField(
            model_name='memory',
            name='confidence_score',
            field=models.FloatField(default=0.8, help_text='How confident the system is about this memory (0.0-1.0). Auto-set on pattern match.'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(help_text='Response to return when pattern is detected'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='intent_key',
            field=models.CharField(db_index=True, help_text="Unique identifier for this FAQ (e.g., 'creator', 'password_reset')", max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_pattern',
            field=models.CharField(help_text='Pattern to match in user messages (case-insensitive)', max_length=100),
        ),
        migrations.AlterField(
            model_name='memory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='importance',
            field=models.PositiveSmallIntegerField(db_index=True, default=3, help_text='1=low (casual mention), 5=high (core identity). Used for context ranking.'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Updated when memory is used in prompt context', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='intent',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='message',
            name='sentiment',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='nlpevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='nlpevent',
            name='intent',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='nlpevent',
            name='sentiment',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ragquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ragquery',
            name='sources',
            field=models.JSONField(blank=True, default=list, help_text='[{chunk_id: 123, text: "...", page: 2}, ...]'),
        ),
        migrations.AlterField(
            model_name='responsecache',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='responsecache',
            name='is_web_result',
            field=models.BooleanField(default=False, help_text='If True, uses short TTL from TAVILY_CACHE_TTL_SECONDS'),
        ),
        migrations.AlterField(
            model_name='responsecache',
            name='normalized_question',
            field=models.TextField(help_text='Lowercase, punctuation removed for deduplication'),
        ),
        migrations.AlterField(
            model_name='responsecache',
            name='question_hash',
            field=models.CharField(db_index=True, help_text='SHA-256 hash of normalized question for O(1) lookup', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='responsecache',
            name='ttl_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Cache duration in seconds. None = permanent (FAQ), 900 = 15min (web results)', null=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='conv_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', '-uploaded_at'], name='doc_user_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['processed', '-uploaded_at'], name='doc_processed_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='chunk_doc_index_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', '-importance'], name='mem_user_importance_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', '-last_accessed_at'], name='mem_user_accessed_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='msg_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpevent',
            index=models.Index(fields=['user', '-created_at'], name='nlp_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpevent',
            index=models.Index(fields=['intent', 'created_at'], name='nlp_intent_created_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpevent',
            index=models.Index(fields=['sentiment', 'created_at'], name='nlp_sentiment_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ragquery',
            index=models.Index(fields=['user', '-created_at'], name='rag_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ragquery',
            index=models.Index(fields=['document', '-created_at'], name='rag_doc_created_idx'),
        ),
        migrations.AddIndex(
            model_name='responsecache',
            index=models.Index(fields=['-hits'], name='cache_hits_idx'),
        ),
        migrations.AddIndex(
            model_name='responsecache',
            index=models.Index(fields=['created_at'], name='cache_created_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeanalysis',
            index=models.Index(fields=['user', '-created_at'], name='resume_user_created_idx'),
        ),
    ]
