# Generated by Django 5.0.7 on 2026-05-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('login', 'Login')], default='register', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
