# Generated by Django 5.0.7 on 2026-06-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_adminregistrationrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailotp',
            options={'ordering': ['-created_at'], 'verbose_name': 'email OTP', 'verbose_name_plural': 'email OTPs'},
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminregistrationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='adminregistrationrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminregistrationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('login', 'Login')], db_index=True, default='register', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], db_index=True, default='user', max_length=20),
        ),
        migrations.AddIndex(
            model_name='adminregistrationrequest',
            index=models.Index(fields=['status', '-created_at'], name='admreq_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email', 'purpose'], name='otp_email_purpose_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['expires_at'], name='otp_expires_idx'),
        ),
    ]
